#-------------------------------------------------
#
# Project created by QtCreator 2015-03-05T23:12:44
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

TARGET = QtCrypt
TEMPLATE = app

INCLUDEPATH += $$_PRO_FILE_PWD_/libsodium/include
INCLUDEPATH += $$_PRO_FILE_PWD_/libsodium/include/sodium
INCLUDEPATH += $$_PRO_FILE_PWD_/quazip
INCLUDEPATH += $$_PRO_FILE_PWD_/zlib-1.2.8

DEFINES += SODIUM_STATIC
DEFINES += QUAZIP_STATIC

HEADERS += \
    libsodium/crypto_auth/hmacsha256/cp/api.h \
    libsodium/crypto_auth/hmacsha512/cp/api.h \
    libsodium/crypto_auth/hmacsha512256/cp/api.h \
    libsodium/crypto_box/curve25519xsalsa20poly1305/ref/api.h \
    libsodium/crypto_core/hsalsa20/ref2/api.h \
    libsodium/crypto_core/salsa20/ref/api.h \
    libsodium/crypto_core/salsa2012/ref/api.h \
    libsodium/crypto_core/salsa208/ref/api.h \
    libsodium/crypto_generichash/blake2/ref/api.h \
    libsodium/crypto_generichash/blake2/ref/blake2-impl.h \
    libsodium/crypto_generichash/blake2/ref/blake2.h \
    libsodium/crypto_hash/sha256/cp/api.h \
    libsodium/crypto_hash/sha512/cp/api.h \
    libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.h \
    libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h \
    libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h \
    libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h \
    libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h \
    libsodium/crypto_pwhash/scryptsalsa208sha256/sysendian.h \
    libsodium/crypto_scalarmult/curve25519/donna_c64/api.h \
    libsodium/crypto_scalarmult/curve25519/ref10/api.h \
    libsodium/crypto_scalarmult/curve25519/ref10/fe.h \
    libsodium/crypto_scalarmult/curve25519/ref10/montgomery.h \
    libsodium/crypto_scalarmult/curve25519/ref10/pow225521.h \
    libsodium/crypto_secretbox/xsalsa20poly1305/ref/api.h \
    libsodium/crypto_shorthash/siphash24/ref/api.h \
    libsodium/crypto_sign/ed25519/ref10/api.h \
    libsodium/crypto_sign/ed25519/ref10/base.h \
    libsodium/crypto_sign/ed25519/ref10/base2.h \
    libsodium/crypto_sign/ed25519/ref10/d.h \
    libsodium/crypto_sign/ed25519/ref10/d2.h \
    libsodium/crypto_sign/ed25519/ref10/fe.h \
    libsodium/crypto_sign/ed25519/ref10/ge.h \
    libsodium/crypto_sign/ed25519/ref10/ge_add.h \
    libsodium/crypto_sign/ed25519/ref10/ge_madd.h \
    libsodium/crypto_sign/ed25519/ref10/ge_msub.h \
    libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.h \
    libsodium/crypto_sign/ed25519/ref10/ge_sub.h \
    libsodium/crypto_sign/ed25519/ref10/pow22523.h \
    libsodium/crypto_sign/ed25519/ref10/pow225521.h \
    libsodium/crypto_sign/ed25519/ref10/sc.h \
    libsodium/crypto_sign/ed25519/ref10/sqrtm1.h \
    libsodium/crypto_sign/edwards25519sha512batch/ref/api.h \
    libsodium/crypto_sign/edwards25519sha512batch/ref/fe25519.h \
    libsodium/crypto_sign/edwards25519sha512batch/ref/ge25519.h \
    libsodium/crypto_sign/edwards25519sha512batch/ref/sc25519.h \
    libsodium/crypto_stream/aes128ctr/portable/api.h \
    libsodium/crypto_stream/aes128ctr/portable/common.h \
    libsodium/crypto_stream/aes128ctr/portable/consts.h \
    libsodium/crypto_stream/aes128ctr/portable/int128.h \
    libsodium/crypto_stream/aes128ctr/portable/types.h \
    libsodium/crypto_stream/chacha20/ref/api.h \
    libsodium/crypto_stream/salsa20/amd64_xmm6/api.h \
    libsodium/crypto_stream/salsa20/ref/api.h \
    libsodium/crypto_stream/salsa2012/ref/api.h \
    libsodium/crypto_stream/salsa208/ref/api.h \
    libsodium/crypto_stream/xsalsa20/ref/api.h \
    libsodium/crypto_verify/16/ref/api.h \
    libsodium/crypto_verify/32/ref/api.h \
    libsodium/crypto_verify/64/ref/api.h \
    libsodium/include/sodium/core.h \
    libsodium/include/sodium/crypto_aead_chacha20poly1305.h \
    libsodium/include/sodium/crypto_auth.h \
    libsodium/include/sodium/crypto_auth_hmacsha256.h \
    libsodium/include/sodium/crypto_auth_hmacsha512.h \
    libsodium/include/sodium/crypto_auth_hmacsha512256.h \
    libsodium/include/sodium/crypto_box.h \
    libsodium/include/sodium/crypto_box_curve25519xsalsa20poly1305.h \
    libsodium/include/sodium/crypto_core_hsalsa20.h \
    libsodium/include/sodium/crypto_core_salsa20.h \
    libsodium/include/sodium/crypto_core_salsa2012.h \
    libsodium/include/sodium/crypto_core_salsa208.h \
    libsodium/include/sodium/crypto_generichash.h \
    libsodium/include/sodium/crypto_generichash_blake2b.h \
    libsodium/include/sodium/crypto_hash.h \
    libsodium/include/sodium/crypto_hash_sha256.h \
    libsodium/include/sodium/crypto_hash_sha512.h \
    libsodium/include/sodium/crypto_int32.h \
    libsodium/include/sodium/crypto_int64.h \
    libsodium/include/sodium/crypto_onetimeauth.h \
    libsodium/include/sodium/crypto_onetimeauth_poly1305.h \
    libsodium/include/sodium/crypto_pwhash_scryptsalsa208sha256.h \
    libsodium/include/sodium/crypto_scalarmult.h \
    libsodium/include/sodium/crypto_scalarmult_curve25519.h \
    libsodium/include/sodium/crypto_secretbox.h \
    libsodium/include/sodium/crypto_secretbox_xsalsa20poly1305.h \
    libsodium/include/sodium/crypto_shorthash.h \
    libsodium/include/sodium/crypto_shorthash_siphash24.h \
    libsodium/include/sodium/crypto_sign.h \
    libsodium/include/sodium/crypto_sign_ed25519.h \
    libsodium/include/sodium/crypto_sign_edwards25519sha512batch.h \
    libsodium/include/sodium/crypto_stream.h \
    libsodium/include/sodium/crypto_stream_aes128ctr.h \
    libsodium/include/sodium/crypto_stream_chacha20.h \
    libsodium/include/sodium/crypto_stream_salsa20.h \
    libsodium/include/sodium/crypto_stream_salsa2012.h \
    libsodium/include/sodium/crypto_stream_salsa208.h \
    libsodium/include/sodium/crypto_stream_xsalsa20.h \
    libsodium/include/sodium/crypto_uint16.h \
    libsodium/include/sodium/crypto_uint32.h \
    libsodium/include/sodium/crypto_uint64.h \
    libsodium/include/sodium/crypto_uint8.h \
    libsodium/include/sodium/crypto_verify_16.h \
    libsodium/include/sodium/crypto_verify_32.h \
    libsodium/include/sodium/crypto_verify_64.h \
    libsodium/include/sodium/export.h \
    libsodium/include/sodium/randombytes.h \
    libsodium/include/sodium/randombytes_salsa20_random.h \
    libsodium/include/sodium/randombytes_sysrandom.h \
    libsodium/include/sodium/runtime.h \
    libsodium/include/sodium/utils.h \
    libsodium/include/sodium/version.h \
    libsodium/include/sodium.h \
    quazip/crypt.h \
    quazip/ioapi.h \
    quazip/JlCompress.h \
    quazip/quaadler32.h \
    quazip/quachecksum32.h \
    quazip/quacrc32.h \
    quazip/quagzipfile.h \
    quazip/quaziodevice.h \
    quazip/quazip.h \
    quazip/quazip_global.h \
    quazip/quazipdir.h \
    quazip/quazipfile.h \
    quazip/quazipfileinfo.h \
    quazip/quazipnewinfo.h \
    quazip/unzip.h \
    quazip/zip.h \
    src/myabstractbar.h \
    src/mycleardir.h \
    src/mycrypt.h \
    src/mydecryptbar.h \
    src/mydecryptthread.h \
    src/mydirthread.h \
    src/myencryptbar.h \
    src/myencryptthread.h \
    src/myfileinfo.h \
    src/myfilesystemmodel.h \
    src/myinterrupt.h \
    src/myloadbar.h \
    src/myloadthread.h \
    src/mymainwindow.h \
    src/mysavebar.h \
    src/mysavethread.h \
    zlib-1.2.8/crc32.h \
    zlib-1.2.8/deflate.h \
    zlib-1.2.8/gzguts.h \
    zlib-1.2.8/inffast.h \
    zlib-1.2.8/inffixed.h \
    zlib-1.2.8/inflate.h \
    zlib-1.2.8/inftrees.h \
    zlib-1.2.8/trees.h \
    zlib-1.2.8/zconf.h \
    zlib-1.2.8/zlib.h \
    zlib-1.2.8/zutil.h

SOURCES += \
    quazip/JlCompress.cpp \
    quazip/qioapi.cpp \
    quazip/quaadler32.cpp \
    quazip/quacrc32.cpp \
    quazip/quagzipfile.cpp \
    quazip/quaziodevice.cpp \
    quazip/quazip.cpp \
    quazip/quazipdir.cpp \
    quazip/quazipfile.cpp \
    quazip/quazipfileinfo.cpp \
    quazip/quazipnewinfo.cpp \
    src/main.cpp \
    src/myabstractbar.cpp \
    src/mycleardir.cpp \
    src/mycrypt.cpp \
    src/mydecryptbar.cpp \
    src/mydecryptthread.cpp \
    src/mydirthread.cpp \
    src/myencryptbar.cpp \
    src/myencryptthread.cpp \
    src/myfileinfo.cpp \
    src/myfilesystemmodel.cpp \
    src/myloadbar.cpp \
    src/myloadthread.cpp \
    src/mymainwindow.cpp \
    src/mysavebar.cpp \
    src/mysavethread.cpp \
    libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c \
    libsodium/crypto_auth/hmacsha256/cp/hmac_hmacsha256.c \
    libsodium/crypto_auth/hmacsha256/cp/verify_hmacsha256.c \
    libsodium/crypto_auth/hmacsha256/auth_hmacsha256_api.c \
    libsodium/crypto_auth/hmacsha512/cp/hmac_hmacsha512.c \
    libsodium/crypto_auth/hmacsha512/cp/verify_hmacsha512.c \
    libsodium/crypto_auth/hmacsha512/auth_hmacsha512_api.c \
    libsodium/crypto_auth/hmacsha512256/cp/hmac_hmacsha512256.c \
    libsodium/crypto_auth/hmacsha512256/cp/verify_hmacsha512256.c \
    libsodium/crypto_auth/hmacsha512256/auth_hmacsha512256_api.c \
    libsodium/crypto_auth/crypto_auth.c \
    libsodium/crypto_box/curve25519xsalsa20poly1305/ref/after_curve25519xsalsa20poly1305.c \
    libsodium/crypto_box/curve25519xsalsa20poly1305/ref/before_curve25519xsalsa20poly1305.c \
    libsodium/crypto_box/curve25519xsalsa20poly1305/ref/box_curve25519xsalsa20poly1305.c \
    libsodium/crypto_box/curve25519xsalsa20poly1305/ref/keypair_curve25519xsalsa20poly1305.c \
    libsodium/crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305_api.c \
    libsodium/crypto_box/crypto_box.c \
    libsodium/crypto_box/crypto_box_easy.c \
    libsodium/crypto_core/hsalsa20/ref2/core_hsalsa20.c \
    libsodium/crypto_core/hsalsa20/core_hsalsa20_api.c \
    libsodium/crypto_core/salsa20/ref/core_salsa20.c \
    libsodium/crypto_core/salsa20/core_salsa20_api.c \
    libsodium/crypto_core/salsa2012/ref/core_salsa2012.c \
    libsodium/crypto_core/salsa2012/core_salsa2012_api.c \
    libsodium/crypto_core/salsa208/ref/core_salsa208.c \
    libsodium/crypto_core/salsa208/core_salsa208_api.c \
    libsodium/crypto_generichash/blake2/ref/blake2b-ref.c \
    libsodium/crypto_generichash/blake2/ref/generichash_blake2b.c \
    libsodium/crypto_generichash/blake2/generichash_blake2_api.c \
    libsodium/crypto_generichash/crypto_generichash.c \
    libsodium/crypto_hash/sha256/cp/hash_sha256.c \
    libsodium/crypto_hash/sha256/hash_sha256_api.c \
    libsodium/crypto_hash/sha512/cp/hash_sha512.c \
    libsodium/crypto_hash/sha512/hash_sha512_api.c \
    libsodium/crypto_hash/crypto_hash.c \
    libsodium/crypto_onetimeauth/poly1305/donna/auth_poly1305_donna.c \
    libsodium/crypto_onetimeauth/poly1305/donna/verify_poly1305_donna.c \
    libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c \
    libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305_api.c \
    libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305_try.c \
    libsodium/crypto_onetimeauth/crypto_onetimeauth.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt-common.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c \
    libsodium/crypto_pwhash/scryptsalsa208sha256/scrypt_platform.c \
    libsodium/crypto_scalarmult/curve25519/donna_c64/base_curve25519_donna_c64.c \
    libsodium/crypto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.c \
    libsodium/crypto_scalarmult/curve25519/ref10/base_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_0_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_1_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_add_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_copy_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_cswap_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_frombytes_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_invert_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_mul121666_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_mul_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_sq_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_sub_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/fe_tobytes_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/ref10/scalarmult_curve25519_ref10.c \
    libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519_api.c \
    libsodium/crypto_scalarmult/crypto_scalarmult.c \
    libsodium/crypto_secretbox/xsalsa20poly1305/ref/box_xsalsa20poly1305.c \
    libsodium/crypto_secretbox/xsalsa20poly1305/secretbox_xsalsa20poly1305_api.c \
    libsodium/crypto_secretbox/crypto_secretbox.c \
    libsodium/crypto_secretbox/crypto_secretbox_easy.c \
    libsodium/crypto_shorthash/siphash24/ref/shorthash_siphash24.c \
    libsodium/crypto_shorthash/siphash24/shorthash_siphash24_api.c \
    libsodium/crypto_shorthash/crypto_shorthash.c \
    libsodium/crypto_sign/ed25519/ref10/fe_0.c \
    libsodium/crypto_sign/ed25519/ref10/fe_1.c \
    libsodium/crypto_sign/ed25519/ref10/fe_add.c \
    libsodium/crypto_sign/ed25519/ref10/fe_cmov.c \
    libsodium/crypto_sign/ed25519/ref10/fe_copy.c \
    libsodium/crypto_sign/ed25519/ref10/fe_frombytes.c \
    libsodium/crypto_sign/ed25519/ref10/fe_invert.c \
    libsodium/crypto_sign/ed25519/ref10/fe_isnegative.c \
    libsodium/crypto_sign/ed25519/ref10/fe_isnonzero.c \
    libsodium/crypto_sign/ed25519/ref10/fe_mul.c \
    libsodium/crypto_sign/ed25519/ref10/fe_neg.c \
    libsodium/crypto_sign/ed25519/ref10/fe_pow22523.c \
    libsodium/crypto_sign/ed25519/ref10/fe_sq.c \
    libsodium/crypto_sign/ed25519/ref10/fe_sq2.c \
    libsodium/crypto_sign/ed25519/ref10/fe_sub.c \
    libsodium/crypto_sign/ed25519/ref10/fe_tobytes.c \
    libsodium/crypto_sign/ed25519/ref10/ge_add.c \
    libsodium/crypto_sign/ed25519/ref10/ge_double_scalarmult.c \
    libsodium/crypto_sign/ed25519/ref10/ge_frombytes.c \
    libsodium/crypto_sign/ed25519/ref10/ge_madd.c \
    libsodium/crypto_sign/ed25519/ref10/ge_msub.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p1p1_to_p2.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p1p1_to_p3.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p2_0.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p2_dbl.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p3_0.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p3_dbl.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p3_to_cached.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p3_to_p2.c \
    libsodium/crypto_sign/ed25519/ref10/ge_p3_tobytes.c \
    libsodium/crypto_sign/ed25519/ref10/ge_precomp_0.c \
    libsodium/crypto_sign/ed25519/ref10/ge_scalarmult_base.c \
    libsodium/crypto_sign/ed25519/ref10/ge_sub.c \
    libsodium/crypto_sign/ed25519/ref10/ge_tobytes.c \
    libsodium/crypto_sign/ed25519/ref10/keypair.c \
    libsodium/crypto_sign/ed25519/ref10/open.c \
    libsodium/crypto_sign/ed25519/ref10/sc_muladd.c \
    libsodium/crypto_sign/ed25519/ref10/sc_reduce.c \
    libsodium/crypto_sign/ed25519/ref10/sign.c \
    libsodium/crypto_sign/ed25519/sign_ed25519_api.c \
    libsodium/crypto_sign/edwards25519sha512batch/ref/fe25519_edwards25519sha512batch.c \
    libsodium/crypto_sign/edwards25519sha512batch/ref/ge25519_edwards25519sha512batch.c \
    libsodium/crypto_sign/edwards25519sha512batch/ref/sc25519_edwards25519sha512batch.c \
    libsodium/crypto_sign/edwards25519sha512batch/ref/sign_edwards25519sha512batch.c \
    libsodium/crypto_sign/edwards25519sha512batch/sign_edwards25519sha512batch_api.c \
    libsodium/crypto_sign/crypto_sign.c \
    libsodium/crypto_stream/aes128ctr/portable/afternm_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/beforenm_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/common_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/consts_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/int128_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/stream_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/portable/xor_afternm_aes128ctr.c \
    libsodium/crypto_stream/aes128ctr/stream_aes128ctr_api.c \
    libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.c \
    libsodium/crypto_stream/chacha20/stream_chacha20_api.c \
    libsodium/crypto_stream/salsa20/ref/stream_salsa20_ref.c \
    libsodium/crypto_stream/salsa20/ref/xor_salsa20_ref.c \
    libsodium/crypto_stream/salsa20/stream_salsa20_api.c \
    libsodium/crypto_stream/salsa2012/ref/stream_salsa2012.c \
    libsodium/crypto_stream/salsa2012/ref/xor_salsa2012.c \
    libsodium/crypto_stream/salsa2012/stream_salsa2012_api.c \
    libsodium/crypto_stream/salsa208/ref/stream_salsa208.c \
    libsodium/crypto_stream/salsa208/ref/xor_salsa208.c \
    libsodium/crypto_stream/salsa208/stream_salsa208_api.c \
    libsodium/crypto_stream/xsalsa20/ref/stream_xsalsa20.c \
    libsodium/crypto_stream/xsalsa20/ref/xor_xsalsa20.c \
    libsodium/crypto_stream/xsalsa20/stream_xsalsa20_api.c \
    libsodium/crypto_stream/crypto_stream.c \
    libsodium/crypto_verify/16/ref/verify_16.c \
    libsodium/crypto_verify/16/verify_16_api.c \
    libsodium/crypto_verify/32/ref/verify_32.c \
    libsodium/crypto_verify/32/verify_32_api.c \
    libsodium/crypto_verify/64/ref/verify_64.c \
    libsodium/crypto_verify/64/verify_64_api.c \
    libsodium/randombytes/salsa20/randombytes_salsa20_random.c \
    libsodium/randombytes/sysrandom/randombytes_sysrandom.c \
    libsodium/randombytes/randombytes.c \
    libsodium/sodium/core.c \
    libsodium/sodium/runtime.c \
    libsodium/sodium/utils.c \
    libsodium/sodium/version.c \
    quazip/unzip.c \
    quazip/zip.c \
    zlib-1.2.8/adler32.c \
    zlib-1.2.8/compress.c \
    zlib-1.2.8/crc32.c \
    zlib-1.2.8/deflate.c \
    zlib-1.2.8/gzclose.c \
    zlib-1.2.8/gzlib.c \
    zlib-1.2.8/gzread.c \
    zlib-1.2.8/gzwrite.c \
    zlib-1.2.8/infback.c \
    zlib-1.2.8/inffast.c \
    zlib-1.2.8/inflate.c \
    zlib-1.2.8/inftrees.c \
    zlib-1.2.8/trees.c \
    zlib-1.2.8/uncompr.c \
    zlib-1.2.8/zutil.c

FORMS += \
    src/myabstractbar.ui \
    src/mymainwindow.ui
